### ISSUE TITLE
Remove use of sql.php from code

### ISSUE THREAD

**Issue by stephenjust** [supertuxkart/stk-addons#10]
When STKAddons was originally written, a set of database functions were written to speed up development. This all uses the (deprecated as of PHP 5.5) mysql module.

To replace this,we are using PDO, through a DBConnection class written in a more modern style. This also has the advantage of being more secure, as all queries run through it are prepared statements. This removes the need for explicit escaping of strings in queries, for example.

As such, all references to functions in sql.php should be removed. Helper functions can be added to DBConnection.class.php.as the need arises.

**Comment by leyyin** [comment]
Fixed in the new code.
