### ISSUE TITLE
Remove the non-power of 2 textures warning

### ISSUE THREAD

**Issue by qwertychouskie** [supertuxkart/stk-addons#109]
"Warning: This addon may not display correctly on some systems. It uses textures that may not be compatible with all video cards."

As far as I know, systems that don't support NPoT textures can even display STK's interface correctly anyways, so having this warning seems weird.

**Comment by deveee** [comment]
There is a fallback for GPUs that don't support npot textures (it was broken by vlj after STK 0.8.1 but now it works). From what I know it incorrectly detects that the npot extension is available only for android emulator and we have a graphical restriction for it. And for desktop GPUs I think that it will work everywhere (works for me even on intel i965 on windows that doesn't have npot support). So I think that indeed the warning doesn't have much sense.
