### ISSUE TITLE
Allow stk-addons give user existing token if saved-session is true

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-addons#113]
so user in andorid and pc can login with password to get the same token without having to create different accounts or editing players.xml manually.

Add something like in public static function create before $session_id = Util::getClientSessionId():

if ($save_session) select cid from v3_client_sessions where uid = $uid, if found, $client_session = get($cid, $uid);

and then $client_session->setOnline() and goes on (like in the saved-session of api)

Important for network stk so players don't have to relogin everytime

**Comment by leyyin** [comment]
I don't really understand your code, please make a Pull request.
