### ISSUE TITLE
Sign in Ravenbridge mansion says “RAVENBRIDGE ESTATE”

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-addons#124]
The entrance sign in Ravenbridge mansion says “RAVENBRIDGE ESTATE” but the track is called “Ravenbridge mansion”. Is this inconsistency intended?

**Comment by auriamg** [comment]
noun
1. an extensive area of land in the country, usually with a large house, owned by one person, family, or organization.

i.e. the estate is the area of land, and the mansion is on the estate. I see no issue there
