### ISSUE TITLE
Rescue point in reverse Ravenbridge Mansion respawns you on banana

### ISSUE THREAD

**Issue by Wuzzy2** [supertuxkart/stk-addons#125]
https://satoshiupload.com/images/dNfmeckA7y.jpg

If you drive Ravenbridge Mansion in reverse mode and you reset behind the banana in above screenshot, you will respawn on the banana and collect it immediately.

The banana is on the big curvy cobblestone serpentines that lead up to the road, 2nd level.

**Comment by leyyin** [comment]
Wrong issue tracker, see https://github.com/supertuxkart/stk-code

**Comment by Wuzzy2** [comment]
https://github.com/supertuxkart/stk-code/issues/3846
