### ISSUE TITLE
generate_xml.php accessible by everyone

### ISSUE THREAD

**Issue by MinIsMin** [supertuxkart/stk-addons#130]
Currently everyone can trigger a regeneration of the xml files `news` and `assets` at any time as often as you like by simply going to `generate_xml.php`.
It would be best to add a check if it's called from the web or cronjob (?).

**Comment by leyyin** [comment]
Should be fixed, now `generate_xml.php` is just a [CLI tool ](https://github.com/supertuxkart/stk-addons/blob/master/tools/generate-xml.php)
