### ISSUE TITLE
Add "Valles Marineris" track as an add-on

### ISSUE THREAD

**Issue by luisvallejomohl** [supertuxkart/stk-addons#135]
Hello, there. I have a track which I made called "Valles Marineris". It is a track on Mars, with UFOs and Aliens. I would like to have my track added as an add-on or if possible in the main game. Can you please turn it in to an add-on?

[vallesMarineris.zip](https://github.com/supertuxkart/stk-addons/files/3526985/vallesMarineris.zip)

**Comment by auriamg** [comment]
You can do so yourself here : https://online.supertuxkart.net we don't need to do it for you

**Comment by luisvallejomohl** [comment]
Can you teach me how? I actually don't know how to do that.

**Comment by auriamg** [comment]
After logging in, select "Upload" from the Add-ons menu, and just follow the instructions on screen
