### ISSUE TITLE
pagination(tracks, arenas): empty last pages

### ISSUE THREAD

**Issue by thetric** [supertuxkart/stk-addons#142]
# Current behavior
The last pages of the arena and tracks pagination leads to empty pages:

Arenas:
![image](https://user-images.githubusercontent.com/19861998/80862924-fb66bd80-8c78-11ea-8158-0fd8e4cb6789.png)

Tracks:
![image](https://user-images.githubusercontent.com/19861998/80862930-06215280-8c79-11ea-857e-56d2ac97cc1e.png)

# Expected behavior
All pages of the pagination must display entries. In the screenshots above the arena page must not display the last page 5, the tracks page not page 18 and 19.

**Comment by Benau** [comment]
fixed by #160
