### ISSUE TITLE
Addons installer for non STK approved addons.

### ISSUE THREAD

**Issue by dev01111** [supertuxkart/stk-addons#149]
# Idea - Add a download for a add-ons installer on the website, to install unapproved add-ons.

Create a addons installer, to copy the addons and import them into SuperTuxKart, like <a href="https://github.com/dev01111/estkai">eSTKai</a>, and upload it onto the website for downloads.

**Comment by Benau** [comment]
we have an /installaddon in lobby by the way, unapproved addons are not offically supported ![](https://cdn.lihkg.com/assets/faces/pig/bye.gif)
