### ISSUE TITLE
Valid License.txt not found!

### ISSUE THREAD

**Issue by JYamihud** [supertuxkart/stk-addons#156]
I was trying to upload an addon kart into the website with a dual license of GPL3+ and CC-BY-SA but no matter how I've written the document License.txt in the ZIP, it kept telling me that the file was invalid. I tried coping a format from multiple sources, both with in the game default kart's license files. And from licenses that I could get from addon already published. None work. No matter how I write the license file, it returns the error of the file being invalid.

How should the valid file look?

**Comment by Benau** [comment]
Can you upload the .zip here

**Comment by JYamihud** [comment]
[MoriaNeonSpeedsterSTKAsset.zip](https://github.com/supertuxkart/stk-addons/files/11129786/MoriaNeonSpeedsterSTKAsset.zip)

On the site I'm blenderdumbass ( blenderdumbass@dnmx.org )

This is:

Moria on NeonSpeedster ( from Moria's Race ( open movie project ))

**Comment by Benau** [comment]
It's License.txt and not Lisense.txt as in your .zip

**Comment by JYamihud** [comment]
That's not an error though. You can spell the word both ways.
