### ISSUE TITLE
User pages do not display correctly when username is strictly numeric

### ISSUE THREAD

**Issue by stephenjust** [supertuxkart/stk-addons#17]
User pages do not load correctly in the case that a user has a strictly numeric username. The fields on their user page do not populate correctly.

The root cause of this issue is some old code that allowed user pages to be accessed by either their numeric user ID or their username. I do not believe that any instances where links to user pages are created using only a numeric ID still exist.

The code that supports getting users by numeric ID in users.php should be removed.

**Comment by leyyin** [comment]
Does not affect current code.
