### ISSUE TITLE
Integrating Leyyin's fork

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#28]
We need to merge in leyyin's fork. The current tux family 'master' should probably be moved to a branch (in case of emergency fixes on current server), leyyins then the new fork, which is then to be used on our vps.

How are we going to migrate the current DB to our VPS? Not sure if we should copy addon tracks over (many would need to be ported to work well with the new graphics. Karts don't need porting (afaik), but maybe remove some really low quality karts? What about user ids?

**Comment by hiker** [comment]
The first part still needs to be done: merging leyyins fork with this master, changing the vps to use this repo. Ideally before the rc (in case that we need any changes, we can quickly update the repo, pull again on the vps from github, and be ready to go).

**Comment by stephenjust** [comment]
The old server is now in read-only mode.
