### ISSUE TITLE
Strange Search Behaviour

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#51]
If you enter a user name in the user search field, and press return, the search is not performed.

When trying to reproduce this issue I noticed that the search works as expected if you do not press enter (e.g. only enter 'hiker') - then hiker will be shown on the left after a few seconds. But if you press enter, the user list on the left contains all names again.

**Comment by leyyin** [comment]
The page is searching as you type but it should not allow to refresh the page if you press enter
