### ISSUE TITLE
Addon upload preview and zips

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-addons#52]
The upload control tries to display a preview of the uploaded file, but for zips this just adds a long stream of meaningless characters to the page, also making it very slow

![addons_bug](https://cloud.githubusercontent.com/assets/4296971/7149542/cccefb9a-e2dc-11e4-969b-05f6f916dc00.jpg)

**Comment by leyyin** [comment]
In what browser does it happen? I can't reproduce it :/

**Comment by auriamg** [comment]
This was seen in chrome

**Comment by leyyin** [comment]
I never saw this happen, if you experience this, please reopen.
