### ISSUE TITLE
Increase Addon Upload Size Limit

### ISSUE THREAD

**Issue by stephenjust** [supertuxkart/stk-addons#55]
Currently, the addon server has a max upload size set to 8MB, and a maximum POST size of 12MB.
I propose increasing the max upload size to 30MB, max POST size to 35MB, and increasing Apache's timeout from 5 minutes to 10 minutes to allow larger uploads.

**Comment by leyyin** [comment]
Everything sounds good to me :).

**Comment by stephenjust** [comment]
Done.
