### ISSUE TITLE
No notification of new addons

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#56]
the admins need to get an email if a new addon is uploaded, that functionality from the old web page appears to be missing atm.

**Comment by leyyin** [comment]
Hmm, in the old server the notifications were sent to https://sourceforge.net/p/supertuxkart/mailman/supertuxkart-addons/

**Comment by stephenjust** [comment]
Fixing this may be as simple as configuring the new site to email that
mailing list, unless the hooks to send the notifications were removed from
the code.

**Comment by leyyin** [comment]
@auriamg can you add the email 'no-reply@addons.supertuxkart.net' manually as a subscriber to the mailing list? So that it allows to receive mails from that address.

**Comment by auriamg** [comment]
Okay done, this should now work I guess!

**Comment by leyyin** [comment]
It seems to work now.
