### ISSUE TITLE
No Game mode can run

### ISSUE THREAD

**Issue by Moaz93** [supertuxkart/stk-addons#58]
---------------------------
SuperTuxKart crashed :/
---------------------------
SuperTuxKart crashed!
Please hit Ctrl+C to copy to clipboard and signal the problem
to the developers on our forum: http://forum.freegamedev.net/viewforum.php?f=16

Call stack:

 <no symbol available>
 <no symbol available>
 <no symbol available>
---------------------------
OK   
---------------------------

**Comment by leyyin** [comment]
Hi,
Are you sure this is a stk-addons issue? Maybe it is intended for https://github.com/supertuxkart/stk-code.

**Comment by Moaz93** [comment]
sorry i will delete it
thanks for the link i didn't find it myself
