### ISSUE TITLE
Trusted SSL certificates

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-addons#60]
Currently, both versions of stkaddons use self-signed ssl certificates although you can get a trusted ssl certificate for free (e.g. with StartSSL).

It would imo be good to replace the current certificates with trusted ones and configure both versions as https-only.

**Comment by sjal** [comment]
The website doesn't have SSL certificate as well. I don't know how exactly it was two years ago, but nowadays getting and automating renewal of the certificate through Let's Encrypt is pretty easy

**Comment by qwertychouskie** [comment]
IMO this should be a P1.  Firefox displays a scary warning when logging in about the connection not being secure.  It should be tested if older STK versions will cooperate with a cert change.

**Comment by qwertychouskie** [comment]
@leyyin This can be closed now, right?
