### ISSUE TITLE
Missing or incorrectly formatted XML information causes missing icons in stk

### ISSUE THREAD

**Issue by hiker** [supertuxkart/stk-addons#62]
The downloaded addons.xml files does not contain icon information anymore. E.g.:
```
<kart id="alternative-tux" name="Alternative Tux" file="http://addons.supertuxkart.net/dl/1201809349552da39065bf9.zip" date="1429054353" uploader="Auria" designer="Joost Verdoorn" description="" format="2" revision="1" status="449" size="1947574" min-include-version="" max-include-version="" license="" image-list="" rating="2.000"/>
```
This causes bug 2334 in stk (missing icons). There is a new (though empty) field image-list.

**Comment by leyyin** [comment]
Image-list is something to do with accessing the images metadata through a JSON API, not sure why that is even there.
See example: http://stkaddons.net/xml/assets.xml and JSON file http://stkaddons.net/karts/alternative-tux/images.json.
And apparently some other fields like the license are missing :/.
But I did manage to fix it now, see -> http://stkaddons.net/xml/assets.xml.
