### ISSUE TITLE
List of STK-owned domains and redirects 

### ISSUE THREAD

**Issue by konstin** [supertuxkart/stk-addons#64]
Currently, there are quite a few domains owned by the STK team, e.g. http://addons.supertuxkart.net, http://issues.supertuxkart.net, but there's also http://supertuxkart.org. There is also a number of special redirects, e.g. http://supertuxkart.sourceforge.net/forum. We should create a list of all of them so that they can be used throughout the project. And if, not yet done, someone should create a redirect for the latest download links for windows/mac/linux.

**Comment by qwertychouskie** [comment]
Also, the http://supertuxkart.org/ site should be a 401 or 403 redirect, not a frame.

**Comment by Benau** [comment]
Now in stk vps currently it uses:

download.supertuxkart.net -> https://sourceforge.net/projects/supertuxkart/files/latest/download

docs.supertuxkart.net -> https://supertuxkart.net/Community

donate.supertuxkart.net -> https://supertuxkart.net/Donate

issues.supertuxkart.net -> https://github.com/supertuxkart/stk-code/issues?state=open

privacy.supertuxkart.net -> https://supertuxkart.net/Privacy

terms.supertuxkart.net -> https://supertuxkart.net/Terms

Also all of the above can be visited with supertuxkart.org too!

 ![](https://lihkg.com/assets/faces/pigxm/dance2.gif) ![](https://lihkg.com/assets/faces/pigxm/dance.gif) ![](https://lihkg.com/assets/faces/pigxm/dance2.gif) ![](https://lihkg.com/assets/faces/pigxm/dance.gif) ![](https://lihkg.com/assets/faces/pigxm/dance2.gif) ![](https://lihkg.com/assets/faces/pigxm/dance.gif)
