### ISSUE TITLE
Addons website removing files from uploaded addons

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-addons#69]
A contributor got his music files removed :

```
"Some invalid files were found in the uploaded add-on. These files have been removed from the archive: after_the_flames.music, JoshWoodward-AttS-03-AfterTheFlames-NoVox.ogg"
```

maybe the list of allowed file types should be carefully studied to avoid stripping useful files

See https://github.com/supertuxkart/stk-code/issues/2481

**Comment by leyyin** [comment]
I updated the whitelist to allow both `ogg` and `music` files, hopefully it is fixed.
