### ISSUE TITLE
Notify addon submitter when posting notes

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-addons#72]
When updating notes, or approving an addon, we should send an email to the submitted of the addon to notify them (I'm pretty sure it doesn't do that atm)

**Comment by qwertychouskie** [comment]
Also for the bug tracker.

**Comment by leyyin** [comment]
@auriamg does the email not send when updating notes? I can't seem to reproduce it on my local instance.
Notifying the addon submiter when posting notes was there from the [start].(https://github.com/supertuxkart/stk-addons/blob/master/include/Addon.class.php#L1047)

**Comment by auriamg** [comment]
Hmm I seem to remember asking on IRC and being told that it didn't work, but it would seem that I remember incorrectly or that this wasn't accurate information, as I just tested it and indeed it does work. Sorry about the false bug report
