### ISSUE TITLE
arena  single player  support

### ISSUE THREAD

**Issue by annopnod** [supertuxkart/stk-addons#76]
please change multiplayer arena to support single player mode
![screenshot from 2016-12-05 17 09 21](https://cloud.githubusercontent.com/assets/6957642/20881197/ca2cbaca-bb0d-11e6-988d-0b598e0ab73a.png)

**Comment by Benau** [comment]
It requires addon authors to make the arena single player-able, (adding navmesh), not something STK team will do

https://supertuxkart.net/Legacy:New_drivelines#Navmeshes

**Comment by auriamg** [comment]
Hi, add-ons are not officially supported by us. Standard arenas support single-player, but for addons you would need to contact the author of the addon and ask they to add multiplayer support in their track.
