### ISSUE TITLE
Support for account deletion

### ISSUE THREAD

**Issue by Meriipu** [supertuxkart/stk-addons#77]
I have not found a way to delete my account. 

I suppose this might have unwanted side effects if your account has uploaded things though?

**Comment by auriamg** [comment]
We can disable an account if you want, though that's not "true" deletion. If you really do want true deletion then this would require work indeed

**Comment by leyyin** [comment]
Done, and up on the server, check your user `Settings`.
The delete account page will give you the option to also delete all your addons.
If you do not wish to delete all your addons, then the addons will be orphaned with no uploader.
