### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-addons#78]
No idea if it's easy to do, I never looked how it actually works. But it would be nice if stats could show Android OS.

Based on recent statistics:
http://addons.supertuxkart.net/stats/?clients
The git2017* versions come from Android. So it's already noticeable and it may be much more when stable release will happen (though no idea how much, currently there is ~750 active installations).

In hardware_stats.cpp it should be enough?
```
#if defined(ANDROID)
    json.add("os_android", 1);
#endif

#if !defined(ANDROID) && defined(__linux__)
    json.add("os_linux", 1);
    json.add("os_unix", 1);
#endif
```

**Comment by leyyin** [comment]
The hardware stats json is used for the stats server that is currently not processing data only collecting it. The addition of that could be valuable in the future.

Regarding the graph from the addons page, those values are computed from the [user agent](https://github.com/supertuxkart/stk-addons/blob/master/download.php#L54)

The user agent header looks something like this:
`SuperTuxKart/<version> (<Operating System>)`

I guess somwhere the android version sets the version to the git string and the OS to Linux.

**Comment by deveee** [comment]
It's in http request. I added separate os name for Android:
https://github.com/supertuxkart/stk-code/commit/48d94e10a7aaa9f9c0e7ef3bc02dada967719bef

There is still a problem with STK_VERSION (the reason that there are git2017xxyy versions). Currently I use it to force extracting new assets when new stk version is installed. The stable 0.9.3 version will use the same STK_VERSION as desktop version, so generally it should be ok. But it's possible that some critical issues will be found i.e. in data/shaders and I will have to use STK_VERSION="0.9.3-2" to force data extraction. Maybe I will add separate constant for android in assets manager. Or we can ignore build number in version string (use 0.9.3 when 0.9.3-xxx is defined) on stk-addons side.

**Comment by leyyin** [comment]
It seems to display fine for Android http://addons.supertuxkart.net/stats/?clients
