### ISSUE TITLE
Cannot upload add-on

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-addons#79]
When trying to upload an add-on :

```
addons.supertuxkart.net is currently unable to handle this request.
HTTP ERROR 500

```
No further information was shown

**Comment by auriamg** [comment]
Thanks, but I still get an error, a different one this time:

`Unexpected exception: The path specified is not a directory = "/tmp/stk-uploads"If this is ever visible, that's a bug!`

**Comment by leyyin** [comment]
@auriamg Try now.
I also discovered some corrupted addons that do not have file entries :/, will try to come up with a solution

**Comment by auriamg** [comment]
Now I got this when trying to upload sources:
`
File Exception: "/tmp/stk-uploads/1509145759-farm.zip/farm.zip" is not a file/link or it does not exist
`

**Comment by leyyin** [comment]
I can't seem to reproduce it, can you give me the addon and/or zip you are trying to upload.

**Comment by auriamg** [comment]
I have attached the zip to this ticket, I'm trying to add it as source to this addon:
https://addons.supertuxkart.net/addons.php?type=tracks&name=bovine-barnyard_1
[farm.zip](https://github.com/supertuxkart/stk-addons/files/1424556/farm.zip)

**Comment by leyyin** [comment]
The problem is that the directory flattening is non destructive. The code tries to reduce/flatten the directory tree to a single level.
```
Error = `Failed to move file = "/tmp/stk-uploads/1509361234-farm.zip/farm/textures/barn_wall.jpg" to new location = "/tmp/stk-uploads/1509361234-farm.zip/barn_wall.jpg" because it already exists` 
```
Because the `textures/` directory has already a file with the same name, it won't allow you to upload that archive.

This goes into the discussion why is the code flattening directories for all types of archives? 
Even if I made the the flattening destructive, things would get messy for source archives.

Do we desire that addon archives (not source ones) be on the same level?

Any thoughts @hiker @samuncle?

**Comment by auriamg** [comment]
@leyyin Ok thanks for the explanation. I honestly do not really care one way or another, it can stay this way, but I'd at least like a clear error message ("your archive contains 2 files named 'barn_wall.png'" or something like that)

**Comment by hiker** [comment]
+1 :)
I am not sure if flattening might affect the model in blender? Could it be that certain textures are then not found anymore (because they contained a path)?

**Comment by qwertychouskie** [comment]
This is breaking uploading an addon: https://forum.freegamedev.net/viewtopic.php?f=17&t=11126&sid=b9f5630578abbc058b949274579cf0a6&p=82275#p82275

**Comment by auriamg** [comment]
@leyyin This blocks uploading addons containing library nodes, sinces they contain multiple "materials.txt" files

```
FileSystem Exception: Error while trying to flatten the archive. This might happen because files from subdirectories have the same name as files from the root directory. Error = `Failed to move file = "/tmp/stk-uploads/1546532755-canyon_42.zip/library/stklib_barrel_a/materials.xml" to new location = "/tmp/stk-uploads/1546532755-canyon_42.zip/materials.xml" because it already exists`
```

do you think you could look into this?

**Comment by leyyin** [comment]
Well the solution is simple, remove flattening of the directory. 
As was discussed a few months ago I have no idea why flattening was implemented in the first place but I assume it was done for easier parsing of the archive.

I can remove the flattening and make the parsing recursive if this is the only way this can be fixed.

**Comment by qwertychouskie** [comment]
@leyyin Also uploading of https://forum.freegamedev.net/viewtopic.php?f=18&t=11312 is blocked because of this.

**Comment by qwertychouskie** [comment]
It's been almost a whole year... @Benau Could you look into this?  (Also, I'm happy to help test if needed).

**Comment by Benau** [comment]
Now it's fixed
