### ISSUE TITLE
API should be hidden behind a routing scheme

### ISSUE THREAD

**Issue by stephenjust** [supertuxkart/stk-addons#8]
Currently, specific API calls are selected by changing a url parameter in the request to the api. This is not an effective long-term solution.

We should use a URL rewriting scheme to conceal the API file structure from game clients, for example:
  http://api.stkaddons.net/v1/user/login/

This enables us to hide the implementation language from the game client, in case we decide to rewrite the api in a different language once we have a more capable web server. It will also make any api documentation much cleaner, and better conforms to the typical style of RESTful APIs.

**Comment by leyyin** [comment]
This is implemented.
