### ISSUE TITLE
Error you are not logged in

### ISSUE THREAD

**Issue by auriamg** [supertuxkart/stk-addons#83]
I get this message when trying to save "included in game versions", even though I definitely am logged in (and no, I checked my session hasn't expired)

![image](https://user-images.githubusercontent.com/4296971/32149237-bc2045f6-bcd7-11e7-9df2-8d47f6aaf411.png)

**Comment by leyyin** [comment]
I can't seem to reproduce, this happened on a specific addon?

**Comment by leyyin** [comment]
I stumbled into this myself by mistake now, not sure what is happening, one page is saying that I am logged in another says no, weird

**Comment by leyyin** [comment]
Apparently it was setting the session cookie for every sub folder,  this is strange as I never encountered this bug before and it worked fine every time. 

I would clear all the cookies of the addons website, so that there are no more issues.

**Comment by auriamg** [comment]
@leyyin Thank you for all the fixes!

**Comment by 15388734337** [comment]
怎么处理
