### ISSUE TITLE
int overflow for IP > 127 first byte

### ISSUE THREAD

**Issue by Benau** [supertuxkart/stk-addons#90]
Example in kobato branch, hack line stk_host.cpp 581 to m_public_address.setIP(3755991007);
(which is 223.223.223.223)

And then open another stk and connect to that server, in connect_to_server.cpp:129
m_server_address will be m_ip = 2147483647 (and in your stk you will see it send wrong packet to 127.255.255.255)

Though this doens't happen to me on my local stk addon server (with mariadb 10.2.12 and PHP 7.2.1)

(I wonder if auria can remember helping me look at the chatbox crash too....)

**Comment by leyyin** [comment]
Very unlikely to be an overflow as it is an `int unsigned`  
https://github.com/supertuxkart/stk-addons/blob/master/install/install.sql#L310
https://dev.mysql.com/doc/refman/5.7/en/integer-types.html

**Comment by auriamg** [comment]
summary of IRC discussion:

this php line is probably where the issue happens :         $this->ip = (int)$data["ip"];
php uses 32-bit signed ints, doens't have unsigned ints, and only supports float if you want a number over 2G

in the end it may be simpler to just store the IP address as a string. it will take a more bytes but will be easier to debug and diagnose anyway, and as a bonus will even be future-compatible for IPV6

**Comment by Benau** [comment]
https://github.com/supertuxkart/stk-addons/commit/8cf4ac27d0a5f49ca7b26ce36fc24d150ec44e83
?

**Comment by leyyin** [comment]
Ah yes, that would explain the inconsistency, as the addons servers is 32 bits it only supports integers of that size (if it was 64 bits, PHP would have supported int64 integers).
And yes I agree that a string for the IP would be a much more elegant solution.

**Comment by leyyin** [comment]
Updated on server.

**Comment by Benau** [comment]
Now after the php fixes there is regression for Arthur's VPS (with ip 188.x.x.x)

Basically i think we need to remove all int $ip in Server / ClientSession, and in server.php (in api) remove all (int) cast for utf8_encode($_POST['address'])

**Comment by Benau** [comment]
fixed
