### ISSUE TITLE
Can't edit or delete my bug report.

### ISSUE THREAD

**Issue by Taylorcho123** [supertuxkart/stk-addons#99]

**Comment by auriamg** [comment]
It's not clear which bug report you are talking about, could you instead please post a comment into the right bug report to clarify things?

**Comment by Taylorcho123** [comment]
I uploaded this : http://addons.supertuxkart.net/bugs/?bug_id=13
Kart Kiki requires 0.9.3 version of stk but I am using 0.9.1 version right now.

**Comment by qwertychouskie** [comment]
Can confirm, there is no button to close your own bug report.  This report should be re-opened.
